Font loading and text spacing
fusiform/fusiform.github.io pull request #2
Opened 2017-02-01 15:16 UTC by allytart

2017-02-01 15:20 UTC, allytart commented
Minor changes to test font loading. Just need it merged so I can see if fonts load properly on mobile.

2017-02-01 15:31 UTC, alexjmathews requested changes

2017-02-01 15:31 UTC, alexjmathews commented on clinicians.html
> +    <link href="fonts/avenir.css" rel="stylesheet" type="text/css" media="all" />
No importing avenir because its illegal LOL

2017-02-01 15:31 UTC, alexjmathews commented on clinicians.html
> +    <link href='https://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
Use webfont loader instead.

2017-02-01 15:31 UTC, alexjmathews commented on clinicians.html
> +                <div>
Can we take out the comments?

2017-02-01 15:31 UTC, alexjmathews commented on press.html
> +    <link href="fonts/avenir.css" rel="stylesheet" type="text/css" media="all" />
same

2017-02-01 15:31 UTC, alexjmathews commented on clinicians.html
>      <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all" />
This is 404-ing

2017-02-01 15:31 UTC, alexjmathews commented on index.html
>      <title>Fusiform - Fully Digital O&amp;P</title>
faster transition for opening animation

2017-02-02 23:12 UTC, alexjmathews requested changes

2017-02-02 23:12 UTC, alexjmathews commented on index.html
> +                                        <h4 class="colorLR inconsolata">excessive inefficiencies</h4>
@allytart This is running off the page. 

[https://www.dropbox.com/s/2yum8vq82phut3f/Screenshot%25202017-02-02%252018.07.50.png?dl=0](url)

2017-02-03 04:07 UTC, allytart commented on index.html
> +                                        <h4 class="colorLR inconsolata">excessive inefficiencies</h4>
Can't see the attached image :(

2017-02-03 20:06 UTC, alexjmathews approved these changes

2017-02-03 20:06 UTC, merged